# SAM configuration file
version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "ai-drivethru-stack"
s3_bucket = "ai-drivethru-deployments"
s3_prefix = "ai-drivethru"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DatabaseUrl=\"postgresql://user:password@your-rds-endpoint:5432/ai_drivethru\" OpenAIApiKey=\"your-openai-key\" JwtSecret=\"your-jwt-secret\""
image_repositories = []

[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
