"""Add unit_cost to ingredients and additional_cost to menu_item_ingredients

Revision ID: 190e0dcd88ec
Revises: b3ec3307f428
Create Date: 2025-09-20 17:08:05.476295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '190e0dcd88ec'
down_revision: Union[str, Sequence[str], None] = 'b3ec3307f428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False, comment='Cost per unit of this ingredient (e.g., cost per slice of cheese)'))
    op.add_column('menu_item_ingredients', sa.Column('additional_cost', sa.Numeric(precision=10, scale=2), nullable=False, comment='Additional cost when adding extra of this ingredient'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_item_ingredients', 'additional_cost')
    op.drop_column('ingredients', 'unit_cost')
    # ### end Alembic commands ###
