"""Initial database schema

Revision ID: 1d2d869303ab
Revises: 
Create Date: 2025-09-24 23:35:05.491397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d2d869303ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('address', sa.String(length=255), nullable=True, comment='Restaurant address'))
    op.add_column('restaurants', sa.Column('phone', sa.String(length=20), nullable=True, comment='Restaurant phone number'))
    op.add_column('restaurants', sa.Column('hours', sa.String(length=100), nullable=True, comment='Restaurant operating hours'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'hours')
    op.drop_column('restaurants', 'phone')
    op.drop_column('restaurants', 'address')
    # ### end Alembic commands ###
