"""Add missing menu_item_tags table

Revision ID: 7c29fb1fcfff
Revises: 27469c216978
Create Date: 2025-09-18 02:41:21.213899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c29fb1fcfff'
down_revision: Union[str, Sequence[str], None] = '27469c216978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_item_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False, comment='Reference to menu item'),
    sa.Column('tag_id', sa.Integer(), nullable=False, comment='Reference to tag'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu_item_id', 'tag_id', name='uq_menu_item_tag')
    )
    op.create_index(op.f('ix_menu_item_tags_id'), 'menu_item_tags', ['id'], unique=False)
    op.create_index(op.f('ix_menu_item_tags_menu_item_id'), 'menu_item_tags', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_menu_item_tags_tag_id'), 'menu_item_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_item_tags_tag_id'), table_name='menu_item_tags')
    op.drop_index(op.f('ix_menu_item_tags_menu_item_id'), table_name='menu_item_tags')
    op.drop_index(op.f('ix_menu_item_tags_id'), table_name='menu_item_tags')
    op.drop_table('menu_item_tags')
    # ### end Alembic commands ###
