"""add_is_special_to_menu_items

Revision ID: c51ab00a2b47
Revises: 7c29fb1fcfff
Create Date: 2025-09-18 14:50:50.884596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51ab00a2b47'
down_revision: Union[str, Sequence[str], None] = '7c29fb1fcfff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('is_special', sa.Boolean(), nullable=True, comment='Whether this item is a special/featured item'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'is_special')
    # ### end Alembic commands ###
